const ADD_PIZZA = 'app/cart/ADD_PIZZA';
const INCREMENT_PIZZA = 'app/cart/INCREMENT_PIZZA';
const DECREMENT_PIZZA = 'app/cart/DECREMENT_PIZZA';
const DELETE_PIZZA = 'app/cart/DELETE_PIZZA';
const CLEAR_CART = 'app/cart/CLEAR_CART';

export default {
  ADD_PIZZA,
  INCREMENT_PIZZA,
  DECREMENT_PIZZA,
  DELETE_PIZZA,
  CLEAR_CART,
}